# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

require_relative "lib/sigwise/version"

Gem::Specification.new do |spec|
  spec.name = "sigwise"
  spec.version = SigWise::VERSION
  spec.summary = "SigWise API client for Ruby"
  spec.homepage = "https://sigwise.ai/docs"
  spec.license = "Nonstandard"
  spec.required_ruby_version = ">= 2.7"

  spec.files = Dir["lib/**/*.rb", "README.md"]
  spec.require_paths = ["lib"]
end
