# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # Create, rotate and revoke the keys your integrations sign requests with.
    class ApiKeys
      # @api private
      def initialize(client)
        @client = client
      end

      # List API keys.
      #
      # Revoked keys are not listed. Secrets are never returned.
      #
      # `GET /v1/api_keys`
      #
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def list(options = {})
        @client.request("GET", "/v1/api_keys", {}, nil, nil, options)
      end

      # Create an API key.
      #
      # Mints a key ID and signing secret. **The secret is shown only once.**
      #
      # `POST /v1/api_keys`
      #
      # @param body [Hash] the request body
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def create(body, options = {})
        @client.request("POST", "/v1/api_keys", {}, nil, body, options)
      end

      # Update an API key.
      #
      # Rename a key, or deactivate and reactivate it. Use `DELETE` to revoke.
      #
      # `PATCH /v1/api_keys/{key_id}`
      #
      # @param key_id [String]
      # @param body [Hash] the request body
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def update(key_id, body, options = {})
        @client.request("PATCH", "/v1/api_keys/{key_id}", {"key_id" => key_id}, nil, body, options)
      end

      # Revoke an API key.
      #
      # The key stops authenticating immediately. Its ID is never reissued.
      #
      # `DELETE /v1/api_keys/{key_id}`
      #
      # @param key_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [nil]
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def revoke(key_id, options = {})
        @client.request("DELETE", "/v1/api_keys/{key_id}", {"key_id" => key_id}, nil, nil, options)
      end

      # Rotate an API key's secret.
      #
      # Keeps the key ID and replaces the secret. The old secret stops working
      # immediately; the new one is returned only once.
      #
      # `POST /v1/api_keys/{key_id}/rotate`
      #
      # @param key_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def rotate(key_id, options = {})
        @client.request("POST", "/v1/api_keys/{key_id}/rotate", {"key_id" => key_id}, nil, nil, options)
      end
    end
  end
end
