# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # Prepaid balance, the billing ledger, and card top-ups.
    class Billing
      # @api private
      def initialize(client)
        @client = client
      end

      # Get the prepaid balance.
      #
      # `GET /v1/billing`
      #
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def get_balance(options = {})
        @client.request("GET", "/v1/billing", {}, nil, nil, options)
      end

      # List ledger entries.
      #
      # One page of the billing ledger, newest first. Pass the previous page's
      # `next_cursor` as `cursor` to continue; it is empty on the last page.
      #
      # `GET /v1/billing/ledger`
      #
      # @param params [Hash] query parameters: type, limit, cursor
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def list_ledger(params = {}, options = {})
        @client.request("GET", "/v1/billing/ledger", {}, params, nil, options)
      end

      # Start a card top-up.
      #
      # Creates a hosted Stripe Checkout Session for the amount and returns its URL. The
      # balance is credited only once Stripe confirms the payment. Returns `503` when
      # card payments are not configured.
      #
      # `POST /v1/billing/checkout`
      #
      # @param body [Hash] the request body
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def create_checkout(body, options = {})
        @client.request("POST", "/v1/billing/checkout", {}, nil, body, options)
      end

      # Get a top-up's status.
      #
      # Whether the Checkout Session's payment has been credited to the balance yet.
      #
      # `GET /v1/billing/checkout/{session_id}`
      #
      # @param session_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def get_checkout(session_id, options = {})
        @client.request("GET", "/v1/billing/checkout/{session_id}", {"session_id" => session_id}, nil, nil, options)
      end
    end
  end
end
