# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # Events and messages are the evidence an object's answers are computed from.
    class Events
      # @api private
      def initialize(client)
        @client = client
      end

      # Ingest events.
      #
      # Records one or more events or messages about an object.
      #
      # **Asynchronous (default).** Returns `202` immediately and schedules a debounced
      # analysis: a burst of events for one object coalesces into a single analysis once
      # activity settles. Read the answers with `GET /v1/objects/{object_id}` or receive
      # them by webhook.
      #
      # **Synchronous (`wait: true`).** Blocks on the analyzer and returns the verdict
      # inline with `200`, so you can approve, review or block content before publishing
      # it. Restrict scoring to some signals with `signals`, and score the request's
      # events in isolation with `include_history: false`.
      #
      # Returns `402` when the tenant's balance is empty. A synchronous request returns
      # `429` when the account already has the maximum number of synchronous analyses in
      # flight (8 by default), and `503` with `analyzer_busy` when the analyzer is
      # throttling; the events are recorded either way, so don't resend them: after
      # `Retry-After`, request an analysis with `POST /v1/objects/{object_id}/analyze`
      # and read the answers with `GET /v1/objects/{object_id}` or by webhook.
      #
      # **Event retention.** With `event_retention` `after_analysis` (see `PATCH
      # /v1/settings`), a synchronous request's events are scored in memory and never
      # written, so after an error nothing is recorded: resend the request (the
      # `Idempotency-Key` is released for it). Asynchronous events are stored only until
      # their analysis has read them.
      #
      # **Safe retries.** Send an `Idempotency-Key` header (any unique string, such as a
      # UUID) and retry with the same key after a timeout or a `5xx`: the events are
      # recorded once. A repeat of an asynchronous request is answered like the first
      # and carries `Idempotent-Replayed: true`. A repeat of a synchronous request
      # returns `409` without analyzing (or charging) again; read the verdict with `GET
      # /v1/objects/{object_id}`. Reusing a key for a different object returns `422`.
      # Keys are remembered for 24 hours.
      #
      # `POST /v1/objects/{object_id}/events`
      #
      # @param object_id [String]
      # @param body [Hash] the request body
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def ingest(object_id, body, options = {})
        @client.request("POST", "/v1/objects/{object_id}/events", {"object_id" => object_id}, nil, body, options)
      end

      # List an object's events.
      #
      # Returns up to the 200 most recent events and messages recorded for the object,
      # newest first.
      #
      # `GET /v1/objects/{object_id}/events`
      #
      # @param object_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def list(object_id, options = {})
        @client.request("GET", "/v1/objects/{object_id}/events", {"object_id" => object_id}, nil, nil, options)
      end
    end
  end
end
