# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # The authenticated principal and tenant settings.
    class Me
      # @api private
      def initialize(client)
        @client = client
      end

      # Get the current principal.
      #
      # Returns the tenant the credential belongs to. For console tokens it also returns
      # the signed-in user and whether they finished onboarding.
      #
      # `GET /v1/me`
      #
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def get(options = {})
        @client.request("GET", "/v1/me", {}, nil, nil, options)
      end
    end
  end
end
