# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # An object is anything you want answers about: a user, a listing, an order.
    class Objects
      # @api private
      def initialize(client)
        @client = client
      end

      # Re-analyze every object.
      #
      # Schedules a re-analysis of every object the tenant has, typically after changing
      # signal configuration. Jobs run at bulk priority, behind live traffic. Each
      # analysis is billed.
      #
      # `POST /v1/analyze`
      #
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def analyze_all(options = {})
        @client.request("POST", "/v1/analyze", {}, nil, nil, options)
      end

      # List objects.
      #
      # Returns one page of objects with their latest analysis.
      #
      # `q` is either a substring of the object ID or display name, or a signal query
      # such as `is_scammer > 90 and trust_score < 1` (see [Search and
      # conditions](https://sigwise.ai/docs/guides/queries)).
      #
      # `GET /v1/objects`
      #
      # @param params [Hash] query parameters: q, sort, limit, offset, cursor
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def list(params = {}, options = {})
        @client.request("GET", "/v1/objects", {}, params, nil, options)
      end

      # Get an object's analysis.
      #
      # Returns the latest answer for each signal computed for the object, plus the
      # configured signals that have no answer yet (`pending`).
      #
      # Reads are cached for a few seconds; the `X-Cache` header says whether this one
      # was a `HIT` or a `MISS`. Ingesting events and completed analyses invalidate the
      # cache.
      #
      # `GET /v1/objects/{object_id}`
      #
      # @param object_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def get(object_id, options = {})
        @client.request("GET", "/v1/objects/{object_id}", {"object_id" => object_id}, nil, nil, options)
      end

      # Delete an object's data.
      #
      # Deletes everything stored about the object: its events, answers, rolling
      # summary, queued analysis, rule state and firings, and webhook deliveries. Use it
      # when one of your users asks to be forgotten.
      #
      # Billing ledger entries keep the object id as financial records. The object
      # reappears only if you send new events for it.
      #
      # `DELETE /v1/objects/{object_id}`
      #
      # @param object_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [nil]
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def delete(object_id, options = {})
        @client.request("DELETE", "/v1/objects/{object_id}", {"object_id" => object_id}, nil, nil, options)
      end

      # Get an object's compacted history.
      #
      # Older events are folded into a rolling summary so the analyzer gets a bounded
      # payload while keeping long-term signal. This returns that summary and the
      # compaction cursor.
      #
      # `GET /v1/objects/{object_id}/state`
      #
      # @param object_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def get_state(object_id, options = {})
        @client.request("GET", "/v1/objects/{object_id}/state", {"object_id" => object_id}, nil, nil, options)
      end

      # Re-analyze an object.
      #
      # Schedules an immediate re-analysis without a new event, for example right after
      # adding a signal. Runs at live priority; poll `GET /v1/objects/{object_id}` for
      # the result. Returns `404` when the object has no events.
      #
      # `POST /v1/objects/{object_id}/analyze`
      #
      # @param object_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def analyze(object_id, options = {})
        @client.request("POST", "/v1/objects/{object_id}/analyze", {"object_id" => object_id}, nil, nil, options)
      end
    end
  end
end
