# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # An object is anything you want answers about: a user, a listing, an order.
    class Overview
      # @api private
      def initialize(client)
        @client = client
      end

      # Get tenant overview.
      #
      # Tenant-wide totals and per-signal value distributions, computed with SQL
      # aggregates.
      #
      # `GET /v1/overview`
      #
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def get(options = {})
        @client.request("GET", "/v1/overview", {}, nil, nil, options)
      end
    end
  end
end
