# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # Events and messages are the evidence an object's answers are computed from.
    class Playground
      # @api private
      def initialize(client)
        @client = client
      end

      # Try signals on sample events.
      #
      # Scores sample events against your enabled signals and returns the answers,
      # **without recording anything**: no object is created, the events and answers are
      # not stored, and no rule or webhook fires. Use it to check how your signals judge
      # content before you send real traffic, or after you change a signal's
      # instructions.
      #
      # The events are scored on their own, with no history. Restrict the run to some
      # signals with `signals`. At most 50 events per run.
      #
      # The analysis is real, so it is charged to your balance like any other and
      # counted as a synchronous analysis in your usage. Returns `402` when the balance
      # is empty, `429` when the account already has the maximum number of synchronous
      # analyses in flight, and `503` with `analyzer_busy` when the analyzer is
      # throttling.
      #
      # `POST /v1/playground`
      #
      # @param body [Hash] the request body
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def run(body, options = {})
        @client.request("POST", "/v1/playground", {}, nil, body, options)
      end
    end
  end
end
