# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # A rule fires an action (email, Slack or webhook) when an object's signal values
    # cross a line you care about, such as `is_scammer >= 90`.
    class RuleFirings
      # @api private
      def initialize(client)
        @client = client
      end

      # List rule firings.
      #
      # The audit log of rule firings and their action outcomes, newest first.
      #
      # `GET /v1/rule_firings`
      #
      # @param params [Hash] query parameters: rule_id, object_id, limit
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def list(params = {}, options = {})
        @client.request("GET", "/v1/rule_firings", {}, params, nil, options)
      end
    end
  end
end
