# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # A rule fires an action (email, Slack or webhook) when an object's signal values
    # cross a line you care about, such as `is_scammer >= 90`.
    class Rules
      # @api private
      def initialize(client)
        @client = client
      end

      # List rules.
      #
      # `GET /v1/rules`
      #
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def list(options = {})
        @client.request("GET", "/v1/rules", {}, nil, nil, options)
      end

      # Create a rule.
      #
      # The condition is validated against the tenant's signals, and a `webhook` action
      # must reference a registered endpoint subscribed to `rule.triggered`.
      #
      # `POST /v1/rules`
      #
      # @param body [Hash] the request body
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def create(body, options = {})
        @client.request("POST", "/v1/rules", {}, nil, body, options)
      end

      # Get a rule.
      #
      # `GET /v1/rules/{rule_id}`
      #
      # @param rule_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def get(rule_id, options = {})
        @client.request("GET", "/v1/rules/{rule_id}", {"rule_id" => rule_id}, nil, nil, options)
      end

      # Update a rule.
      #
      # Omitted fields are left unchanged. The resulting condition and action are
      # re-validated.
      #
      # `PATCH /v1/rules/{rule_id}`
      #
      # @param rule_id [String]
      # @param body [Hash] the request body
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def update(rule_id, body, options = {})
        @client.request("PATCH", "/v1/rules/{rule_id}", {"rule_id" => rule_id}, nil, body, options)
      end

      # Delete a rule.
      #
      # `DELETE /v1/rules/{rule_id}`
      #
      # @param rule_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [nil]
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def delete(rule_id, options = {})
        @client.request("DELETE", "/v1/rules/{rule_id}", {"rule_id" => rule_id}, nil, nil, options)
      end
    end
  end
end
