# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # The authenticated principal and tenant settings.
    class Settings
      # @api private
      def initialize(client)
        @client = client
      end

      # Get tenant settings.
      #
      # `GET /v1/settings`
      #
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def get(options = {})
        @client.request("GET", "/v1/settings", {}, nil, nil, options)
      end

      # Update tenant settings.
      #
      # Omitted fields are left unchanged.
      #
      # Limiting `event_retention` (`days` or `after_analysis`) also removes the sample
      # message text kept in every object's rolling summary, since the summary outlives
      # the events it was built from.
      #
      # `PATCH /v1/settings`
      #
      # @param body [Hash] the request body
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def update(body, options = {})
        @client.request("PATCH", "/v1/settings", {}, nil, body, options)
      end
    end
  end
end
