# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # A signal is a question you ask about every object, such as "is this a scammer?"
    # (`noul`), "how trustworthy is this user?" (`score`) or "what is their buyer
    # intent?" (`choice`).
    class Signals
      # @api private
      def initialize(client)
        @client = client
      end

      # List signals.
      #
      # `GET /v1/signals`
      #
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def list(options = {})
        @client.request("GET", "/v1/signals", {}, nil, nil, options)
      end

      # Create or update a signal.
      #
      # Creates the signal, or replaces its definition. `instructions` and `criteria`
      # are passed to the analyzer verbatim; the shape of `criteria` depends on `type`:
      #
      # | `type` | `criteria` |
      # |----------|------------------------------------------------------|
      # | `noul` | object with optional `true` / `false` descriptions |
      # | `score` | ordered array of level descriptions, low to high |
      # | `choice` | object mapping each option to a description or null |
      #
      # Creating a signal does not analyze existing objects unless the tenant setting
      # `auto_backfill_signals` is on; start a backfill explicitly with `POST
      # /v1/signals/{key}/backfill`.
      #
      # `PUT /v1/signals/{key}`
      #
      # @param key [String]
      # @param body [Hash] the request body
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def upsert(key, body, options = {})
        @client.request("PUT", "/v1/signals/{key}", {"key" => key}, nil, body, options)
      end

      # Delete a signal.
      #
      # `DELETE /v1/signals/{key}`
      #
      # @param key [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [nil]
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def delete(key, options = {})
        @client.request("DELETE", "/v1/signals/{key}", {"key" => key}, nil, nil, options)
      end

      # Get backfill estimate and progress.
      #
      # Returns how many existing objects have no answer for the signal and what
      # analyzing them would cost now, plus the progress of the most recent backfill
      # (`null` if none was started).
      #
      # `GET /v1/signals/{key}/backfill`
      #
      # @param key [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def get_backfill(key, options = {})
        @client.request("GET", "/v1/signals/{key}/backfill", {"key" => key}, nil, nil, options)
      end

      # Start a backfill.
      #
      # Re-analyzes, for this signal only, every existing object that has no answer for
      # it. Jobs run at bulk priority so they never delay live ingest. Each analysis is
      # billed. Returns `409` if the signal is disabled.
      #
      # `POST /v1/signals/{key}/backfill`
      #
      # @param key [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def start_backfill(key, options = {})
        @client.request("POST", "/v1/signals/{key}/backfill", {"key" => key}, nil, nil, options)
      end
    end
  end
end
