# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # Analysis volume, spend and token usage over a date range.
    class Usage
      # @api private
      def initialize(client)
        @client = client
      end

      # Get usage.
      #
      # Analyses, spend and tokens over an inclusive UTC date range (at most 366 days),
      # with a zero-filled daily series and breakdowns by model, source (`async` /
      # `sync`) and signal. Defaults to the last 30 days.
      #
      # `GET /v1/usage`
      #
      # @param params [Hash] query parameters: from, to
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def get(params = {}, options = {})
        @client.request("GET", "/v1/usage", {}, params, nil, options)
      end
    end
  end
end
