# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # Webhook endpoints receive a signed `POST` for the event types they subscribe to:
    # `analysis.completed` each time an analysis completes, and `rule.triggered` when
    # a rule with a webhook action fires.
    class Webhooks
      # @api private
      def initialize(client)
        @client = client
      end

      # List webhook endpoints.
      #
      # `GET /v1/webhooks`
      #
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def list(options = {})
        @client.request("GET", "/v1/webhooks", {}, nil, nil, options)
      end

      # Register a webhook endpoint.
      #
      # Registers an endpoint and returns its signing secret. **The secret is shown only
      # once**; store it to verify deliveries.
      #
      # `POST /v1/webhooks`
      #
      # @param body [Hash] the request body
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def create(body, options = {})
        @client.request("POST", "/v1/webhooks", {}, nil, body, options)
      end

      # Get a webhook endpoint.
      #
      # `GET /v1/webhooks/{endpoint_id}`
      #
      # @param endpoint_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def get(endpoint_id, options = {})
        @client.request("GET", "/v1/webhooks/{endpoint_id}", {"endpoint_id" => endpoint_id}, nil, nil, options)
      end

      # Update a webhook endpoint.
      #
      # Omitted fields are left unchanged.
      #
      # `PATCH /v1/webhooks/{endpoint_id}`
      #
      # @param endpoint_id [String]
      # @param body [Hash] the request body
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def update(endpoint_id, body, options = {})
        @client.request("PATCH", "/v1/webhooks/{endpoint_id}", {"endpoint_id" => endpoint_id}, nil, body, options)
      end

      # Delete a webhook endpoint.
      #
      # Removes the endpoint and its deliveries.
      #
      # `DELETE /v1/webhooks/{endpoint_id}`
      #
      # @param endpoint_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [nil]
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def delete(endpoint_id, options = {})
        @client.request("DELETE", "/v1/webhooks/{endpoint_id}", {"endpoint_id" => endpoint_id}, nil, nil, options)
      end
    end
  end
end
