# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  module Resources
    # Webhook endpoints receive a signed `POST` for the event types they subscribe to:
    # `analysis.completed` each time an analysis completes, and `rule.triggered` when
    # a rule with a webhook action fires.
    class WebhookDeliveries
      # @api private
      def initialize(client)
        @client = client
      end

      # List webhook deliveries.
      #
      # Recent deliveries, newest first. Filter with `status=dead` to inspect the
      # dead-letter queue.
      #
      # `GET /v1/webhook_deliveries`
      #
      # @param params [Hash] query parameters: status, endpoint_id, limit
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def list(params = {}, options = {})
        @client.request("GET", "/v1/webhook_deliveries", {}, params, nil, options)
      end

      # Replay a delivery.
      #
      # Re-queues a delivery (for example one in the dead-letter queue) for another
      # attempt.
      #
      # `POST /v1/webhook_deliveries/{delivery_id}/replay`
      #
      # @param delivery_id [String]
      # @param options [Hash] per-call :timeout, :max_retries and :headers
      # @return [Hash, Array, nil] the decoded response
      # @raise [SigWise::ApiError]
      # @raise [SigWise::ConnectionError]
      def replay(delivery_id, options = {})
        @client.request("POST", "/v1/webhook_deliveries/{delivery_id}/replay", {"delivery_id" => delivery_id}, nil, nil, options)
      end
    end
  end
end
