# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

require "sigwise/version"
require "sigwise/errors"
require "sigwise/client"
require "sigwise/webhook"

# SigWise API client.
#
#     sigwise = SigWise::Client.new("your_key_id", "your_secret")
#     object = sigwise.objects.get("user-42")
module SigWise
end
