# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

require "base64"
require "json"
require "net/http"
require "openssl"
require "securerandom"
require "uri"
require "sigwise/resources/me"
require "sigwise/resources/overview"
require "sigwise/resources/objects"
require "sigwise/resources/events"
require "sigwise/resources/signals"
require "sigwise/resources/settings"
require "sigwise/resources/webhooks"
require "sigwise/resources/webhook_deliveries"
require "sigwise/resources/rules"
require "sigwise/resources/rule_firings"
require "sigwise/resources/api_keys"
require "sigwise/resources/billing"
require "sigwise/resources/usage"

module SigWise
  # SigWise API client.
  #
  #     sigwise = SigWise::Client.new("your_key_id", "your_secret")
  #     object = sigwise.objects.get("user-42")
  #
  # Every request is signed with the API key's secret: the client sends the key
  # ID and a short-lived HS256 token bound to the request's method and path. The
  # secret itself is never sent.
  class Client
    DEFAULT_BASE_URL = "https://api.sigwise.ai"

    # How long each request token is valid for, in seconds (the API allows 300).
    TOKEN_TTL = 60
    RETRY_STATUSES = [408, 429, 500, 502, 503, 504].freeze
    IDEMPOTENT = %w[GET HEAD PUT DELETE OPTIONS].freeze

    # The authenticated principal and tenant settings.
    # @return [Resources::Me]
    attr_reader :me
    # An object is anything you want answers about: a user, a listing, an order.
    # @return [Resources::Overview]
    attr_reader :overview
    # An object is anything you want answers about: a user, a listing, an order.
    # @return [Resources::Objects]
    attr_reader :objects
    # Events and messages are the evidence an object's answers are computed from.
    # @return [Resources::Events]
    attr_reader :events
    # A signal is a question you ask about every object, such as "is this a scammer?" (`noul`), "how trustworthy is this user?" (`score`) or "what is their buyer intent?" (`choice`).
    # @return [Resources::Signals]
    attr_reader :signals
    # The authenticated principal and tenant settings.
    # @return [Resources::Settings]
    attr_reader :settings
    # Webhook endpoints receive a signed `POST` for the event types they subscribe to: `analysis.completed` each time an analysis completes, and `rule.triggered` when a rule with a webhook action fires.
    # @return [Resources::Webhooks]
    attr_reader :webhooks
    # Webhook endpoints receive a signed `POST` for the event types they subscribe to: `analysis.completed` each time an analysis completes, and `rule.triggered` when a rule with a webhook action fires.
    # @return [Resources::WebhookDeliveries]
    attr_reader :webhook_deliveries
    # A rule fires an action (email, Slack or webhook) when an object's signal values cross a line you care about, such as `is_scammer >= 90`.
    # @return [Resources::Rules]
    attr_reader :rules
    # A rule fires an action (email, Slack or webhook) when an object's signal values cross a line you care about, such as `is_scammer >= 90`.
    # @return [Resources::RuleFirings]
    attr_reader :rule_firings
    # Create, rotate and revoke the keys your integrations sign requests with.
    # @return [Resources::ApiKeys]
    attr_reader :api_keys
    # Prepaid balance, the billing ledger, and card top-ups.
    # @return [Resources::Billing]
    attr_reader :billing
    # Analysis volume, spend and token usage over a date range.
    # @return [Resources::Usage]
    attr_reader :usage

    # @param api_key [String, nil] the API key ID. Defaults to ANALYZE_API_KEY.
    # @param secret [String, nil] the key's signing secret. Defaults to ANALYZE_SECRET.
    # @param base_url [String, nil] defaults to ANALYZE_BASE_URL, then the production API.
    # @param timeout [Numeric] seconds, per attempt (30)
    # @param max_retries [Integer] applies to idempotent requests only (2)
    # @param headers [Hash{String => String}] extra headers for every request
    def initialize(api_key = nil, secret = nil, base_url: nil, timeout: 30, max_retries: 2, headers: {})
      api_key = presence(api_key) || presence(ENV["ANALYZE_API_KEY"])
      secret = presence(secret) || presence(ENV["ANALYZE_SECRET"])
      if api_key.nil? || secret.nil?
        raise ArgumentError,
              "SigWise: an API key and its secret are required. Pass them to Client.new or set ANALYZE_API_KEY and ANALYZE_SECRET."
      end

      @api_key = api_key
      @secret = secret
      @base_url = (presence(base_url) || presence(ENV["ANALYZE_BASE_URL"]) || DEFAULT_BASE_URL).chomp("/")
      @timeout = timeout.to_f
      @max_retries = max_retries
      @headers = headers

      @me = Resources::Me.new(self)
      @overview = Resources::Overview.new(self)
      @objects = Resources::Objects.new(self)
      @events = Resources::Events.new(self)
      @signals = Resources::Signals.new(self)
      @settings = Resources::Settings.new(self)
      @webhooks = Resources::Webhooks.new(self)
      @webhook_deliveries = Resources::WebhookDeliveries.new(self)
      @rules = Resources::Rules.new(self)
      @rule_firings = Resources::RuleFirings.new(self)
      @api_keys = Resources::ApiKeys.new(self)
      @billing = Resources::Billing.new(self)
      @usage = Resources::Usage.new(self)
    end

    # Signs the HS256 JWT that authenticates one request: kid names the key,
    # iat/exp bound its lifetime, and htm/htu bind it to the method and path.
    def self.sign_request_token(api_key, secret, method, path, now = nil)
      now ||= Time.now.to_i
      claims = {
        "iat" => now,
        "exp" => now + TOKEN_TTL,
        "jti" => SecureRandom.hex(16),
        "htm" => method.to_s.upcase
      }
      # The server compares htu with the decoded path, so only bind paths it can
      # read back unchanged.
      claims["htu"] = path unless path.match?(/[?#]/)
      header = base64url(JSON.generate("alg" => "HS256", "typ" => "JWT", "kid" => api_key))
      payload = base64url(JSON.generate(claims))
      signature = base64url(OpenSSL::HMAC.digest("sha256", secret, "#{header}.#{payload}"))
      "#{header}.#{payload}.#{signature}"
    end

    # Sends a request. Used by the resource classes.
    #
    # @api private
    # @return [Object, nil] the decoded JSON body, or nil for an empty response
    # @raise [ApiError] for an error response
    # @raise [ConnectionError] when no response arrives
    def request(method, path, path_params = {}, query = nil, body = nil, options = {})
      method = method.to_s.upcase
      raise ArgumentError, "SigWise: method is required" if method.empty?

      raw_path = path.dup
      encoded_path = path.dup
      path_params.each do |name, value|
        value = value.to_s
        raise ArgumentError, "SigWise: #{name} is required" if value.empty?

        raw_path = raw_path.gsub("{#{name}}") { value }
        encoded_path = encoded_path.gsub("{#{name}}") { URI.encode_www_form_component(value).gsub("+", "%20") }
      end

      params = { "api_key" => @api_key }
      (query || {}).each do |key, value|
        next if value.nil?

        params[key.to_s] = value
      end
      url = URI.parse("#{@base_url}#{encoded_path}?#{encode_query(params)}")

      payload = body.nil? ? nil : JSON.generate(body)

      options ||= {}
      retries = IDEMPOTENT.include?(method) ? (options[:max_retries] || @max_retries) : 0
      timeout = (options[:timeout] || @timeout).to_f
      attempt = 0
      loop do
        headers = {
          "Accept" => "application/json",
          "User-Agent" => "sigwise/#{VERSION} (ruby)"
        }.merge(@headers).merge(options[:headers] || {})
        headers["Authorization"] = "Bearer #{self.class.sign_request_token(@api_key, @secret, method, raw_path)}"
        headers["Content-Type"] = "application/json" unless payload.nil?

        begin
          status, response_headers, raw = send_request(method, url, headers, payload, timeout)
        rescue ConnectionError
          raise if attempt >= retries

          backoff(attempt, nil)
          attempt += 1
          next
        end

        return decode(status, response_headers, raw) if status >= 200 && status < 300

        if attempt < retries && RETRY_STATUSES.include?(status)
          backoff(attempt, response_headers["retry-after"])
          attempt += 1
          next
        end

        decoded = decode(status, response_headers, raw)
        error = decoded.is_a?(Hash) && decoded["error"].is_a?(Hash) ? decoded["error"] : {}
        raise ApiError.new(
          status,
          error["code"].is_a?(String) ? error["code"] : "http_#{status}",
          error["message"].is_a?(String) ? error["message"] : "#{method} #{raw_path} returned #{status}",
          decoded,
          response_headers
        )
      end
    end

    def inspect
      "#<#{self.class.name} base_url=#{@base_url.inspect}>"
    end

    def self.base64url(data)
      Base64.urlsafe_encode64(data, padding: false)
    end
    private_class_method :base64url

    private

    def presence(value)
      value.nil? || value.to_s.empty? ? nil : value.to_s
    end

    def encode_query(params)
      params.map do |key, value|
        value = value ? "true" : "false" if value == true || value == false
        "#{URI.encode_www_form_component(key.to_s).gsub('+', '%20')}=#{URI.encode_www_form_component(value.to_s).gsub('+', '%20')}"
      end.join("&")
    end

    def send_request(method, url, headers, payload, timeout)
      klass = Net::HTTP.const_get(method.capitalize)
      req = klass.new(url.request_uri)
      headers.each { |name, value| req[name] = value }
      req.body = payload unless payload.nil?
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = url.scheme == "https"
      http.open_timeout = [timeout, 10.0].min
      http.read_timeout = timeout
      http.write_timeout = timeout if http.respond_to?(:write_timeout=)
      res = http.request(req)
      response_headers = {}
      res.each_header { |name, value| response_headers[name.downcase] = value }
      [res.code.to_i, response_headers, res.body.to_s]
    rescue Timeout::Error, SocketError, IOError, SystemCallError, OpenSSL::SSL::SSLError, Net::ProtocolError => e
      raise ConnectionError, "SigWise: #{method} request failed: #{e.message}"
    end

    def decode(status, headers, raw)
      return nil if status == 204 || raw.empty?

      if headers["content-type"].to_s.include?("json")
        begin
          return JSON.parse(raw)
        rescue JSON::ParserError
          return raw
        end
      end
      raw
    end

    def backoff(attempt, retry_after)
      if retry_after && retry_after.to_s.match?(/\A\d+(\.\d+)?\z/)
        sleep([retry_after.to_f, 60.0].min)
        return
      end
      base = [0.5 * (2**attempt), 8.0].min
      sleep(base / 2 + rand * base / 2)
    end
  end
end
