# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

module SigWise
  # Base class of everything this gem raises on purpose.
  class Error < StandardError; end

  # No response arrived: a network error or a timeout.
  class ConnectionError < Error; end

  # The API answered with an error status.
  class ApiError < Error
    # @return [Integer] the HTTP status code
    attr_reader :status
    # @return [String] the machine-readable error code, e.g. "not_found"
    attr_reader :code
    # @return [Object] the decoded response body
    attr_reader :body
    # @return [Hash{String => String}] the response headers, lower-cased
    attr_reader :headers

    def initialize(status, code, message, body = nil, headers = {})
      super(message)
      @status = status
      @code = code
      @body = body
      @headers = headers
    end
  end
end
