# frozen_string_literal: true

# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

require "json"
require "openssl"

module SigWise
  # Verifies and parses webhook deliveries.
  module Webhook
    # How old a delivery's timestamp may be, in seconds.
    DEFAULT_TOLERANCE = 300

    # A delivery that failed verification.
    class VerificationError < Error; end

    module_function

    # Verifies a webhook delivery: +signature+ (the X-Webhook-Signature header)
    # must be the HMAC-SHA256 of "<timestamp>.<payload>" keyed with the endpoint
    # secret, and +timestamp+ (X-Webhook-Timestamp) must be recent. Pass the raw
    # body, exactly as received.
    #
    # @raise [VerificationError]
    def verify_signature(payload, signature, timestamp, secret, tolerance: DEFAULT_TOLERANCE, now: nil)
      if signature.to_s.empty? || timestamp.to_s.empty?
        raise VerificationError, "missing signature or timestamp header"
      end
      raise VerificationError, "invalid timestamp" unless timestamp.to_s.match?(/\A\d+\z/)

      now ||= Time.now.to_i
      if tolerance.positive? && (now - timestamp.to_i).abs > tolerance
        raise VerificationError, "timestamp outside the tolerance"
      end

      expected = "sha256=" + OpenSSL::HMAC.hexdigest("sha256", secret, "#{timestamp}.#{payload}")
      raise VerificationError, "signature mismatch" unless secure_compare(expected, signature.to_s)

      nil
    end

    # Verifies a webhook delivery (see {verify_signature}) and decodes its body.
    #
    # @return [Hash] the event
    # @raise [VerificationError]
    def construct_event(payload, signature, timestamp, secret, tolerance: DEFAULT_TOLERANCE, now: nil)
      verify_signature(payload, signature, timestamp, secret, tolerance: tolerance, now: now)
      event = begin
        JSON.parse(payload)
      rescue JSON::ParserError
        raise VerificationError, "payload is not valid JSON"
      end
      raise VerificationError, "payload is not a JSON object" unless event.is_a?(Hash)

      event
    end

    # Constant-time string comparison.
    def secure_compare(a, b)
      return false unless a.bytesize == b.bytesize

      result = 0
      a.bytes.zip(b.bytes) { |x, y| result |= x ^ y }
      result.zero?
    end
  end
end
